version: '3.1'
services:
  mysql:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: desarrollo
      MYSQL_DATABASE: semaforo_pis
      MYSQL_USER: desarrollo
      MYSQL_PASSWORD: desarrollo
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
  backend:
    build: 
      context: ./BackEnd
      dockerfile: Dockerfile
    ports:
      - "3006:3006"
    restart: always
    links:
      - mysql
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    links:
      - backend
  fastapi:
    build:
      context: ./FastApi
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - "8000:8000"
volumes:
  mysql: